logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG
    com.github.binarywang.wxpay: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.201/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  pay:
    appId: wxbad0338f56a10d7a
    mchId:
    mchKey:
    keyPath:
    notifyUrl: http://zxoho.natapp1.cc/sell/pay/notify

  miniapp:
    appid: wxbad0338f56a10d7a
    secret:
    token:
    aesKey:
    msgDataForm: JSON


debug: true

