logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG
    com.github.binarywang.wxpay: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 8799
    url: jdbc:mysql://192.168.0.9/selloho?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.9
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: 1
      min-idle: 0
    timeout: 1000
server:
  context-path: /sell

wechat:
  pay:
    appId: wxbad0338f56a10d7a
    mchId:
    mchKey:
    keyPath:
    notifyUrl: http://zxoho.natapp1.cc/sell/pay/notify

  miniapp:
    appid: wxbad0338f56a10d7a
    secret:
    token:
    aesKey:
    msgDataForm: JSON



debug: true

